In [8]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

In [9]:
dataset=pd.read_csv('/content/credit_data.csv')

In [10]:
 dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [11]:
dataset.shape

(21878, 31)

In [12]:
dataset['Class'].value_counts()

Class
0.0    21791
1.0       86
Name: count, dtype: int64

In [13]:
dataset.dropna(subset=['Class'], inplace=True)
dataset['Class']=dataset['Class'].astype(int)

In [14]:
dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [15]:
legit=dataset[dataset.Class==0]
fraud=dataset[dataset.Class==1]

In [16]:
legit.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [17]:
legit.shape

(21791, 31)

In [18]:
legit_sample=legit.sample(n=250)

In [19]:
legit_sample.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
14764,25997,-2.639661,-1.263481,2.537969,3.308483,0.026073,0.857264,0.277682,0.279299,-0.554286,...,-0.029125,0.971785,1.575492,0.207275,0.488232,0.464724,0.655417,-0.258000,204.06,0
20236,30884,1.219728,0.161627,0.358320,0.576943,-0.470642,-0.884142,0.017865,-0.088955,-0.173087,...,0.055980,0.139936,-0.042587,0.559089,0.452741,0.369708,-0.048228,-0.000404,1.50,0
5005,4573,-1.552078,-0.531074,1.974243,1.013701,1.024195,-1.144346,0.002698,0.048984,1.339099,...,-0.181249,-0.715027,0.328461,0.268026,-0.015884,-0.726971,0.026191,0.155041,83.72,0
13072,22942,1.294424,-0.512157,-0.546178,-1.696400,1.395499,3.485397,-1.230323,0.877123,2.955589,...,-0.211257,-0.269834,-0.066246,0.957402,0.638362,-0.710530,0.068991,0.023276,6.70,0
5342,5257,-1.813136,0.969511,1.042145,1.919347,-0.454365,-0.691255,0.003734,0.513163,0.342127,...,-0.073895,-0.017485,-0.334395,0.749738,0.155996,-0.294745,-0.090962,-0.243925,93.99,0

In [20]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [21]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
14764,25997,-2.639661,-1.263481,2.537969,3.308483,0.026073,0.857264,0.277682,0.279299,-0.554286,...,-0.029125,0.971785,1.575492,0.207275,0.488232,0.464724,0.655417,-0.258000,204.06,0
20236,30884,1.219728,0.161627,0.358320,0.576943,-0.470642,-0.884142,0.017865,-0.088955,-0.173087,...,0.055980,0.139936,-0.042587,0.559089,0.452741,0.369708,-0.048228,-0.000404,1.50,0
5005,4573,-1.552078,-0.531074,1.974243,1.013701,1.024195,-1.144346,0.002698,0.048984,1.339099,...,-0.181249,-0.715027,0.328461,0.268026,-0.015884,-0.726971,0.026191,0.155041,83.72,0
13072,22942,1.294424,-0.512157,-0.546178,-1.696400,1.395499,3.485397,-1.230323,0.877123,2.955589,...,-0.211257,-0.269834,-0.066246,0.957402,0.638362,-0.710530,0.068991,0.023276,6.70,0
5342,5257,-1.813136,0.969511,1.042145,1.919347,-0.454365,-0.691255,0.003734,0.513163,0.342127,...,-0.073895,-0.017485,-0.334395,0.749738,0.155996,-0.294745,-0.090962,-0.243925,93.99,0

In [22]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
18466,29526,1.102804,2.829168,-3.932870,4.707691,2.937967,-1.800904,1.672734,-0.300240,-2.783011,...,-0.106994,-0.250050,-0.521627,-0.448950,1.291646,0.516327,0.009146,0.153318,0.68,1
18472,29531,-1.060676,2.608579,-2.971679,4.360089,3.738853,-2.728395,1.987616,-0.357345,-2.757535,...,-0.063168,-0.207385,-0.183261,-0.103679,0.896178,0.407387,-0.130918,0.192177,0.68,1
18773,29753,0.269614,3.549755,-5.810353,5.809370,1.538808,-2.269219,-0.824203,0.351070,-3.759059,...,0.371121,-0.322290,-0.549856,-0.520629,1.378210,0.564714,0.553255,0.402400,0.68,1
18809,29785,0.923764,0.344048,-2.880004,1.721680,-3.019565,-0.639736,-3.801325,1.299096,0.864065,...,0.899931,1.481271,0.725266,0.176960,-1.815638,-0.536517,0.489035,-0.049729,30.30,1
20198,30852,-2.830984,0.885657,1.199930,2.861292,0.321669,0.289966,1.767760,-2.451050,0.069736,...,0.546589,0.334971,0.172106,0.623590,-0.527114,-0.079215,-2.532445,0.311177,104.81,1

In [23]:
new_dataset.shape

(336, 31)

In [24]:
new_dataset.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [25]:
new_dataset['Class'].value_counts()

Class
0    250
1     86
Name: count, dtype: int64

In [26]:
X=new_dataset.drop(columns='Class',axis=1)

In [27]:
Y=new_dataset['Class']

In [28]:
X.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
14764,25997,-2.639661,-1.263481,2.537969,3.308483,0.026073,0.857264,0.277682,0.279299,-0.554286,...,0.184286,-0.029125,0.971785,1.575492,0.207275,0.488232,0.464724,0.655417,-0.258000,204.06
20236,30884,1.219728,0.161627,0.358320,0.576943,-0.470642,-0.884142,0.017865,-0.088955,-0.173087,...,-0.144635,0.055980,0.139936,-0.042587,0.559089,0.452741,0.369708,-0.048228,-0.000404,1.50
5005,4573,-1.552078,-0.531074,1.974243,1.013701,1.024195,-1.144346,0.002698,0.048984,1.339099,...,0.241350,-0.181249,-0.715027,0.328461,0.268026,-0.015884,-0.726971,0.026191,0.155041,83.72
13072,22942,1.294424,-0.512157,-0.546178,-1.696400,1.395499,3.485397,-1.230323,0.877123,2.955589,...,-0.025903,-0.211257,-0.269834,-0.066246,0.957402,0.638362,-0.710530,0.068991,0.023276,6.70
5342,5257,-1.813136,0.969511,1.042145,1.919347,-0.454365,-0.691255,0.003734,0.513163,0.342127,...,-0.185088,-0.073895,-0.017485,-0.334395,0.749738,0.155996,-0.294745,-0.090962,-0.243925,93.99

In [29]:
Y.head()

14764    0
20236    0
5005     0
13072    0
5342     0
Name: Class, dtype: int64

In [30]:
scaler=StandardScaler()

In [31]:
Standard_data=scaler.fit_transform(X)

In [32]:
print(Standard_data)

[[ 0.82719185 -0.04133887 -0.7215992  ...  0.58237177 -0.68008629
   0.54040451]
 [ 1.29821898  0.55819506 -0.37364626 ... -0.34384039 -0.02992044
  -0.38882144]
 [-1.23773247  0.12761097 -0.54277556 ... -0.24588244  0.36242117
  -0.01164451]
 ...
 [ 1.18920902  0.41060038  0.45359533 ...  0.44789489  0.98675039
  -0.39258311]
 [ 1.1922933   0.51221887 -0.32910665 ...  0.36336213 -0.15441381
  -0.256704  ]
 [ 1.2951347  -0.07105973 -0.19686799 ... -3.61383017  0.75650448
   0.08510398]]

In [33]:
X=Standard_data

In [34]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [35]:
print(X.shape,X_train.shape,X_test.shape)

(336, 30) (268, 30) (68, 30)

In [36]:
model=LogisticRegression()

In [37]:
model.fit(X_train,Y_train)

LogisticRegression()

In [38]:
training_data_prediction=model.predict(X_train)
accuracy_for_training=accuracy_score(Y_train,training_data_prediction)

In [39]:
print(accuracy_for_training)

0.9850746268656716

In [40]:
testing_data_prediction=model.predict(X_test)
accuracy_for_testing=accuracy_score(testing_data_prediction,Y_test)

In [41]:
print(accuracy_for_testing)

0.9852941176470589

In [42]:
input_data = (0, -1.359807134, -0.072781173, 2.536346738, 1.378155224,
              -0.33832077, 0.462387778, 0.239598554, 0.098697901,
              0.36378697, 0.090794172, -0.551599533, -0.617800856,
              -0.991389847, -0.311169354, 1.468176972, -0.470400525,
              0.207971242, 0.02579058, 0.40399296, 0.251412098,
              -0.018306778, 0.277837576, -0.11047391, 0.066928075,
              0.128539358, -0.189114844, 0.133558377, -0.021053053,
              149.62)

# Convert input_data to a numpy array and reshape it to (1, -1) before transforming
input_data_as_array = np.asarray(input_data).reshape(1, -1)
input_data_scaled = scaler.transform(input_data_as_array)

prediction=model.predict(input_data_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [43]:
print(prediction)

[0]

In [44]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, testing_data_prediction))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.94      0.97        17

    accuracy                           0.99        68
   macro avg       0.99      0.97      0.98        68
weighted avg       0.99      0.99      0.99        68

In [45]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, testing_data_prediction)
print(cm)

[[51  0]
 [ 1 16]]

In [46]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, testing_data_prediction))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.94      0.97        17

    accuracy                           0.99        68
   macro avg       0.99      0.97      0.98        68
weighted avg       0.99      0.99      0.99        68